// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    // next-env.d.ts is generated by Next on every build and carries a
    // triple-slash reference we neither wrote nor may change — linting it is
    // linting Next's output, not ours.
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/generated/**',
      '**/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // REQUIRED. ESLint's flat-config file discovery only walks **/*.js unless a
    // config names other extensions, so without this `eslint .` silently linted
    // zero TypeScript files and reported a clean pass. A linter that inspects
    // nothing is worse than no linter — it reports success.
    files: ['**/*.{js,mjs,cjs,ts,tsx}'],
    rules: {
      // Phase-0 constraint: no `any` anywhere. An escape hatch here silently
      // becomes an escape hatch in the permission layer later.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': 'warn',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
  {
    // The seed script's whole job is to print a credentials table.
    files: ['apps/api/prisma/seed.ts'],
    rules: { 'no-console': 'off' },
  },
  prettier,
);
